on:
  push:
    branches: 
      - source

name: blogdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: linux-r-${{ hashFiles('depends.Rds') }}
          restore-keys: linux-r-

      - name: Install system dependencies
        #if: runner.os == 'Linux'
        #env:
        #  RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          #Rscript -e "remotes::install_github('r-hub/sysreqs')"
          #sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          #sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_dev("blogdown")
        shell: Rscript {0}

      - name: Install hugo
        run: |
          Rscript -e 'blogdown::install_hugo("0.87.0")'

      - name: Build site
        run: |
          Rscript -e 'blogdown::build_site(build_rmd = FALSE)'
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  
          commit_message: 'Deploy commit: ${{ github.event.head_commit.message }}'
